### ISSUE TITLE
RoboCJK Next Milestones

### ISSUE THREAD

**Issue by BlackFoundry** [BlackFoundryCom/robo-cjk#25]
- [ ] Rethink the GUI for more flexibility of use (get rid of the 3 levels AE DC CG)
- [ ] Make the collaborative tools (GIT, SQL) more general and independant from RoboCJK, but enable their use in RoboCJK
- [ ] Use format closer to traditionnal UFO (with added dedicated libs)
- [ ] Enable easier and more intuitive use of non-linear (beziers) interpolations
- [ ] Include font compiler (VarC, COLRv1…)
- [ ] SQL mode: enable notifications between users (i.e. Mosquito)
